### ISSUE TITLE
Clicking on a user profile results in stack trace

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace#10]
Browsing to, e.g. /users/kerchner@gwu-dot-edu (same for all users in /users) results in stack trace as follows:

```
 Showing /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/_user_info.html.erb where line #8 raised:

undefined method `zotero_userid' for #<User:0x007fd7b6f11c48>

Extracted source (around line #433):

      else
        match = match_attribute_method?(method.to_s)
        match ? attribute_missing(match, *args, &block) : super
      end
    end


Trace of template inclusion: /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/_profile.html.erb, /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/_profile_tabs.html.erb, /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/show.html.erb
```

Zotero integration is not required, from what I can tell, but may want to test whether implementing this integration resolves the stack trace or not.

**Comment by mjgiarlo** [comment]
Doh!  Temporary workaround:
1. Copy `app/views/users/_user_info.html.erb` into your app
2. Change the `if` check on line 8 to be `if  Sufia.config.arkivo_api && user.zotero_userid.present?`

Let me know if that works for you.  If so I can start in on a patch and updated releases.

**Comment by kerchner** [comment]
@mjgiarlo Yup, that workaround resolved it.  Thanks!   Shall I create a ticket?

**Comment by mjgiarlo** [comment]
Please do! I have time to work on it today, methinks.
