### ISSUE TITLE
Rename "GW Affiliation" to "GW Unit"

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace#130]
I know, it's controversial, but it's been bothering me.  Let's at least discuss.

**Comment by kilahimm** [comment]
@kerchner I will say that when some SC staff asked about this on the deposit form they were receptive to the explanation for the change.

**Comment by kerchner** [comment]
As discussed, this will bring the app in line with the deposit form - and as noted above, the label change on the deposit form, for the same field, was received positively by the SC team.
