### ISSUE TITLE
Replace Passenger 404, 500, ect pages

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace#142]
Provide GW branded or more meaningful error pages for passenger to serve.

**Comment by kerchner** [comment]
The 404 page looks pretty good and the links to the contact page and help page seem to work - try https://scholarspace.library.gwu.edu/asdfasdf

I'd have to think about how to provoke an error 500 response.

**Comment by kilahimm** [comment]
It's probably more the 500 error pages, basically situations in which the rails app fails all together.  Granted we wouldn't expect these in production, but they can happen.

**Comment by kerchner** [comment]
Ah, right.  And so then those would be more a passenger configuration, as you noted.

**Comment by kerchner** [comment]
Closing as a wontfix.  This will be done in GWSS 2.0 with https://github.com/gwu-libraries/scholarspace-sufia7/issues/37
