### ISSUE TITLE
Add route for /admin/queue

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace#179]
Currently /admin/queue is not working, because we haven't added it in routes.rb (I think).  This would allow administrators with a more convenient view into the resque queues.

See example at https://github.com/psu-stewardship/scholarsphere/blob/6a6eb043f679abb2a8418c661ba771e89dfea122/config/routes.rb#L19-L25

Also see note added into the README in 6.4.0, at https://github.com/projecthydra/sufia/blob/bc9763fcc7fb6213d5a58b2f2166d747f4f5dea5/README.md#monitor-background-workers

**Comment by kerchner** [comment]
And/or the solution may lie with defining `Sufia::ResqueAdmin` (and `Sufia::StatsAdmin`) in the initializers, as noted here:  https://github.com/projecthydra/sufia/blob/bc9763fcc7fb6213d5a58b2f2166d747f4f5dea5/config/routes.rb#L124-L140

**Comment by kilahimm** [comment]
Moving this into m1.2.0 to aid in job troubleshooting
