### ISSUE TITLE
Adding options to "type of work" drop down menu

### ISSUE THREAD

**Issue by rareleah** [gwu-libraries/scholarspace#255]
Hello,

Can you add the following types to the "type of work" drop down menu in ScholarSpace?
Thesis
Dissertation
Pre-print
Post-print

Thank you!
Leah

**Comment by kerchner** [comment]
As per discussion with @rareleah , we are adding Thesis, but Preprint and Postprint will require more discussion.

**Comment by rareleah** [comment]
Hi Dan, has "thesis" been added yet? 
Thanks!

**Comment by kerchner** [comment]
I've temporarily patched the deployment (try again now).  I'll soon be deploying 1.6.0 which includes it, so we don't have to be living with patches.
