### ISSUE TITLE
Add GW theme to tag cloud text color

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace#41]
See if we can tone done the default color scheme

**Comment by StudioZut** [comment]
The tags have inline styling generated by the tagcloud js: https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/jquery.tagcloud.js

**Comment by kilahimm** [comment]
Not sure if this is how PSU is handling color overrides in ScholarSphere, but they changed the tagcloud.js file to the following: https://github.com/psu-stewardship/scholarsphere/blob/master/app/assets/javascripts/sufia/tagcloud.js

**Comment by StudioZut** [comment]
Thanks @kilahimm that does the trick.
