### ISSUE TITLE
iOS issue with Share Your Work

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/scholarspace#53]
In portrait view with iOS on my test iPad (iPad Air) the text in the Share Your Work button/link overflows the boundaries of the button. This does not happen in my emulator or on Android test devices.

**Comment by kerchner** [comment]
@kilahimm Can you test this on an iPad?  I tested on my Mac w/browser just to make sure the change didn't negatively impact (and it doesn't) viewing in a browser.  But I don't have easy access to an iPad to test that the PR fixes the issue there.

**Comment by kilahimm** [comment]
Is there a development server i can use to test this against?

**Comment by kilahimm** [comment]
@kerchner this looks good to me in testing on iOS.
