### ISSUE TITLE
Review APP name is light of theming and branding

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace#58]
Should the app name be GW ScholarSpace or just Scholarspace in light of better GW theming and branding?

**Comment by StudioZut** [comment]
Maybe call it GW ScholarSpace but drop the "GW" in the masthead (since it's preceded by the GW Libraries logo)?
Also on branding: do we want more info in the footer?

**Comment by kilahimm** [comment]
:+1: I like that, simple solution to the name view.

Do you think the footer needs to include any items we have on other sites?  I'd defer to @StudioZut for guidance here.

**Comment by kerchner** [comment]
My concern with GW ScholarSpace was that it helps distinguish it from the
other two ScholarSpaces out there.  Might help to avoid any possible
infringement issues later - or mere ambiguity at repository conferences :)

**Comment by StudioZut** [comment]
For the footer, I can add some minimal info along the lines of the Libheader Lite (example: https://wikis.library.gwu.edu/ ). I'll keep the current text there and add the new content below.

**Comment by kilahimm** [comment]
I think it make sense to add those footer items.  RE: the app now though, I forgot about the other Scholarspace apps that are out there.  Maybe there is just another way to stylize the app name on the homepage so that it looks less redundant beside the GW Libraries?

**Comment by StudioZut** [comment]
We could make the logo smaller so that it doesn't read as one line, something like this:
![screenshot from 2015-07-27 13 40 13](https://cloud.githubusercontent.com/assets/1031373/8913126/1d12f672-3465-11e5-9775-c96aecc3c493.png)

**Comment by StudioZut** [comment]
Take a look at the footer in my branch and tell if that will work for this milestone: http://gwdev-zut2.wrlc.org:8888/ 

![screenshot from 2015-07-27 15 08 00](https://cloud.githubusercontent.com/assets/1031373/8915172/615b4508-3471-11e5-9da6-9f1a3792a097.png)

**Comment by kilahimm** [comment]
Footer works for me.  As for the logo and the app name I'll defer to folks with a more designed focused eye.

**Comment by kerchner** [comment]
Closed by #83
