### ISSUE TITLE
Citation of Record Permanent Link

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace#60]
Instead of Citation: on view page for item replace with "Permanent Link: <item_url>"  If not able to dynamically get item URL add canned text.

**Comment by kilahimm** [comment]
This can be accomplished through HTML edit as follows:
app/view/generic_files/_show_descriptions.html.erb

```
<h2>Descriptions</h2>
<dl class="dl-horizontal file-show-term file-show-descriptions">
  <% present_terms(@presenter,@presenter.terms - [:title, :description]) do |r,$
  <dt><%= r.label(term) %></dt>
      <dd><%= r.value(term) %></dd>
  <% end %>
  <dt>Permanent Link</dt>
  <dd><a href="">Citation URL</a></dd>
</dl>
```

**Comment by kilahimm** [comment]
Related to this, citation does not need to be a metadata field in the system.  @kerchner thoughts on this?

**Comment by kilahimm** [comment]
Resolved how to do this where the URL is displayed as a link via Rails:

```
<h2>Descriptions</h2>
<dl class="dl-horizontal file-show-term file-show-descriptions">
  <% present_terms(@presenter,@presenter.terms - [:title, :description]) do |r, term| %>
  <dt><%= r.label(term) %></dt>
      <dd><%= r.value(term) %></dd>
  <% end %>
  <dt>Permanent Link</dt>
  <dd><%= link_to sufia.generic_file_url, sufia.generic_file_path(@generic_file) %></dd>
</dl>
```

**Comment by kerchner** [comment]
@kilahimm Remind me again why we're creating a link on a page which always links to... itself?   Is there a scenario where the metadata (versus just the item) is expected to be exported outside of the system?
