### ISSUE TITLE
Display Links a Clickable

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace#68]
Links show using stock font color instead of the expected light blue for a clickable link.  Can we fix this in the CSS?

**Comment by StudioZut** [comment]
Simple enough, just need to markup the a tags in our stylesheet.

**Comment by kerchner** [comment]
This appears to be improved in the default Sufia 7 CSS as of 7.0.0.rc1 (cc: @studiozut).

**Comment by StudioZut** [comment]
I agree, it seems to be addressed.

**Comment by kerchner** [comment]
Closing as fixed in Sufia 7.
