### ISSUE TITLE
Add GW Rights Statement

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace#90]
Need to add the GW rights statement as a selectable option from the CC list of licenses.

**Comment by kerchner** [comment]
Please provide a URL to the full text of the GW rights statement

**Comment by kilahimm** [comment]
http://library.gwu.edu/scholarspace/license

**Comment by kerchner** [comment]
@kilahimm What should the option be labeled?  And where should it appear in the list; should it appear first (as the default option)?

**Comment by kilahimm** [comment]
@kerchner this should be the default option and first in the list.  The label should be "GW Open Access License"
